enter input mode when press ctrl-[xvt]
fisadev/vim-ctrlp-cmdpalette pull request #10
Opened 2017-10-31 09:11 UTC by hiberabyss

Provide a way to enter input mode even with `let g:ctrlp_cmdpalette_execute = 1` set.

2017-11-02 13:55 UTC, fisadev commented
thanks for your contribution! But I'm not sure I understand what it does exactly. Could you explain to me what changes in behavior? Sorry, I'm not an expert on vim internals by any means :)

2018-01-18 06:05 UTC, hiberabyss commented
Hi @fisadev ,

Sorry for the late reply.

In most cases, I just want to execute command without any arguments, then I could just set `let g:ctrlp_cmdpalette_execute = 1`.

However, in some cases, I may also want to execute vim command with arguments. With this pull request:
* When press `<Enter>`, the vim command will be executed directly;
* When press with `<c-x>` `<c-v>` `<c-t>`, the vim command will not be executed, it stays at the command line and waiting for use's input.

Thanks!

2018-03-13 05:32 UTC, hiberabyss commented
Hi @fisadev ,

Is there any suggestion for this PR?
Thanks!

2018-03-13 14:11 UTC, fisadev commented
Just to be sure, this won't break the default behavior when not using ``g:ctrlp_cmdpalette_execute = 1.``, am I right? The default behavior is to not to execute the command on enter, leaving the prompt for the user to add parameters if he wants to.

2018-03-13 14:14 UTC, fisadev requested changes

2018-03-13 14:14 UTC, fisadev commented on autoload/ctrlp/cmdpalette.vim
> +	endif
A small detail: please change these tabs to spaces ;) (using tabs makes it look with a different indentation level depending on the tool)

2018-03-13 15:42 UTC, hiberabyss commented
Hi @fisadev ,

Have updated the code to use whitespace instead of tab.

For your question, the default behavior is not changed when with `g:ctrlp_cmdpalette_execute = 0` except that a whitespace is appended.

Thanks!

2018-03-13 15:44 UTC, fisadev approved these changes

2018-03-13 15:45 UTC, merged

2018-03-13 15:45 UTC, fisadev commented
Merged! Thanks a lot for the work done :)